### ISSUE TITLE
! "Visual Recognition is not available right now..."

### ISSUE THREAD

**Issue by iGarbo** [watson-developer-cloud/visual-recognition-nodejs#233]
Team, I'm giving a demo to a major customer today at 2:30 today (4 hours from now) using visual recognition to identify damaged packages.

It was working a couple days ago. Today it doesn't.

I upload the same .zip files I used a couple days ago (less than 5MB with more than 50 images), let the blue wheel spin for 6 seconds, then get the error "Visual Recognition is not available right now..."

I get this error both on the standard demo instance (http://visual-recognition-demo.mybluemix.net/train) and my own (http://visual-recognition-nodejs-igarbo-2146.mybluemix.net/train).

![screen shot 2016-10-06 at 9 54 03 am](https://cloud.githubusercontent.com/assets/1667160/19155118/41f2c636-8bab-11e6-8abb-f203c1774da5.png)

[good.zip](https://github.com/watson-developer-cloud/visual-recognition-nodejs/files/513906/good.zip)
[smashed.zip](https://github.com/watson-developer-cloud/visual-recognition-nodejs/files/513905/smashed.zip)

**Comment by kognate** [comment]
Talking to the team now and we are investigating a service-level issue.

**Comment by iGarbo** [comment]
You're the man Joshua. Appreciate the note. I took photos of it working
Monday, so I can sing and dance and wave hands to pull off the demo, but
would love to show it working live! :)

**Comment by kognate** [comment]
The system is back up and running.

**Comment by matt-ny** [comment]
It should be fixed as of about 1:45pm eastern @iGarbo 
Please let us know if you have any more errors

**Comment by iGarbo** [comment]
Working beautifully! Thanks gents!

[image: Inline image 1]

**Comment by iGarbo** [comment]
Demo went fantastically! Great service. Lots of interest. Well done Watson hackers.

![screen shot 2016-10-07 at 10 08 37 am](https://cloud.githubusercontent.com/assets/1667160/19192954/14c3cd9c-8c76-11e6-939b-9e152b0f6431.png)

**Comment by yaalisri** [comment]
I am also getting the same error "Visual Recognition is not available right now..." when i try to train the demo project. Is this fixed now?

**Comment by kognate** [comment]
@yaalisri The demo is working now.

**Comment by yaalisri** [comment]
@kognate It is still not working for me :( I uploaded 2 bundle with more than 50 images and tried to train it but it always throws the same error. Can you also please let me know how to train our service instead of demo?

**Comment by matt-ny** [comment]
Does your zip file contain files or folders with special characters like
accents or non-English letters?  We have a known issue with some encodings
for zip files. The workaround is to recreate your zip file.

This problem would occur with both the demo and the API. However, in
general we recommend the API for training because it is persistent- your
trained classifier is saved for you. The tutorial for the API is here
https://www.ibm.com/watson/developercloud/doc/visual-recognition/classifiers-tutorials.shtml

**Comment by yaalisri** [comment]
@matt-ny Thanks for the reply. Can you please send me any link for tutorial on how to create our own visual recognition service with custom classifiers and use the created API in our node.js application using bluemix?

**Comment by sawantsingh** [comment]
I'm facing the same issue now, please let me know when it is
<img width="1258" alt="screen shot 2017-06-12 at 2 52 34 pm" src="https://user-images.githubusercontent.com/5269016/27027376-cd605066-4f7e-11e7-8880-76b288256c6d.png">
 fixed.

**Comment by matt-ny** [comment]
@sawantsingh you may have encountered a temporary issue.  It seems to be fine now.

**Comment by mbesoft** [comment]
It seems to be a reccurent issue ...
![issue](https://user-images.githubusercontent.com/30898798/36494587-b61c0586-1732-11e8-9cfd-d2880200e207.png)
Please could you check and advise ?

**Comment by matt-ny** [comment]
@mbesoft  Not sure what caused that, but the demo appears to be working at this time.  Please try again.

**Comment by mbesoft** [comment]
@matt-ny Thank you for your quick support
Still facing it ... 

[cni.zip](https://github.com/watson-developer-cloud/visual-recognition-nodejs/files/1745035/cni.zip)
[impots.zip](https://github.com/watson-developer-cloud/visual-recognition-nodejs/files/1745036/impots.zip)
[passports.zip](https://github.com/watson-developer-cloud/visual-recognition-nodejs/files/1745037/passports.zip)

is there something wrong with my zip files? 
Thanks for your help

**Comment by matt-ny** [comment]
@mbesoft  Actually, yes, I see that each zip file contains many copies of a single unique image.  Each class must have at least 10 unique images for the service to learn from.  I verified this by comparing the checksums of the images.  

Our error message should be more descriptive though.

Please try again with >=10 unique training images per class.

**Comment by ShubhraMittal1488** [comment]
I am creating a custom classifier and uploading positive and negative zip file, but I am getting the error. "Visual Recognition is not available right now..." Also find attach zips that I am using .
[Asset.zip](https://github.com/watson-developer-cloud/visual-recognition-nodejs/files/1814129/Asset.zip)
[Negative.zip](https://github.com/watson-developer-cloud/visual-recognition-nodejs/files/1814130/Negative.zip)
[Pole.zip](https://github.com/watson-developer-cloud/visual-recognition-nodejs/files/1814131/Pole.zip)
[Wire.zip](https://github.com/watson-developer-cloud/visual-recognition-nodejs/files/1814132/Wire.zip)

**Comment by ShubhraMittal1488** [comment]
I am getting the error "Visual Recognition is not available right now..." while creating custom classifier. I tried multiple times with different positive and negative input zip file with image count>10 per class.
Could anyone help me to resolve this error.

**Comment by matt-ny** [comment]
I received an email with links to 4 zip files from a comment from you which I cannot find here - (edited out?) but was able to download the zip files (wire, asset, etc) and verified they worked for me this morning via the API. Please try your request again.  Training a classifier could take 15 minutes or so.
